# Generated by Django 3.0.8 on 2022-01-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sendMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('msg', models.CharField(max_length=600)),
                ('cdate', models.DateField()),
                ('ctime', models.TimeField()),
            ],
        ),
    ]
