# Generated by Django 3.0.8 on 2022-01-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeMessages', '0002_uploaddoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaddoc',
            name='docfile',
            field=models.FileField(upload_to=None),
        ),
    ]
